export const ADD_FIELD = 'ADD_FIELD';
export const REMOVE_FIELD = 'REMOVE_FIELD';
export const FIELD_MOVE = 'FIELD_MOVE';
export const FIELD_SET_ACTIVE = 'FIELD_SET_ACTIVE';
export const ADD_CHECKBOX_TO_FIELD = 'ADD_CHECKBOX_TO_FIELD';
